name: NuGet

on:
  push:
    tags:
      - "*"
env:
  PROJECT: Run

jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.300

      - name: Get the version
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build
        if: ${{ !env.ACT }}
        run: |
          dotnet pack src/$PROJECT --output __publish__/X /p:Version=${{ steps.get-version.outputs.VERSION }}

        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_NOLOGO: true
          DOTNET_GENERATE_ASPNET_CERTIFICATE: false
          DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
          DOTNET_MULTILEVEL_LOOKUP: 0

      - name: Push
        if: ${{ !env.ACT }}
        run: |
          dotnet nuget push __publish__/X/wk.${{env.PROJECT}}.${{ steps.get-version.outputs.VERSION }}.nupkg \
            -s https://api.nuget.org/v3/index.json \
            -k ${{ secrets.NUGET_TOKEN }}

      - name: Build
        if: ${{ env.ACT }}
        run: |
          dotnet pack src/$PROJECT --output __publish__/X /p:Version=0.0.1
